---
name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
    check-package:
        name: Build & inspect pyownet
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3
          - uses: hynek/build-and-inspect-python-package@v1
